name: Steven Wallace Media
favicon: null
layout_spectrum: 0.9746983253862709
typography_spectrum: 0.6597754582762718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3363210055977106
  lightness: 0.7405019297730178
  saturation: 0.1365185861941427
  rhythmicContrast: 0.5646569181699306
purpose: []
